DROP TABLE IF EXISTS PeerEvents;
CREATE TABLE IF NOT EXISTS PeerEvents (
	EventId VARCHAR(36) PRIMARY KEY,
  PeerId VARCHAR(36) NOT NULL,
	TargetPeerId VARCHAR(36) DEFAULT NULL,
  EventType VARCHAR(16) NOT NULL,
  EventData TEXT NOT NULL,
	Timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Peers;
CREATE TABLE IF NOT EXISTS Peers (
  PeerId VARCHAR(36) PRIMARY KEY,
	Timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS PeerSessions;
CREATE TABLE IF NOT EXISTS PeerSessions (
	SessionId VARCHAR(36) PRIMARY KEY,
  SourcePeerId VARCHAR(36) NOT NULL,
	TargetPeerId VARCHAR(36) NOT NULL,
  Offer TEXT NOT NULL,
	Answer TEXT DEFAULT NULL,
	IsComplete INTEGER(1) NOT NULL DEFAULT 0,
	Timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
